### ISSUE TITLE
Hyphens are not processed properly

### ISSUE THREAD

**Issue by trwnh** [Siphonay/potd_bot#1]
"Ho-oh" got processed as "ho" https://donphan.social/@potd_bot/102150675071673494

The name should be kept as-is; this section is unnecessary:

https://github.com/Siphonay/potd_bot/blob/acc7f7535645e09810823df3fc4d2d5c42dfe191/potd_bot.rb#L27-L31

The only thing that needs to be done is to convert - to _ for the emojo shortcode, which should be stored in a separate variable than pokemon_name.

**Comment by Siphonay** [comment]
This part is necessary because the API puts additional form names even for defaults in the names, that would give results that don't exist as emojis on the server either.
